name: Rclone Dedupe for GoogleDrive Wuxian

on:
  schedule:
    - cron: 0 8 * * 4

jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}
      with:
        args: "dedupe wuxian:Storage --dedupe-mode newest"